Update pandas_utils.py
koaning/scikit-lego pull request #451
Opened 2021-03-24 14:38 UTC by daimonie

One of my pipeline steps (that I wanted to log) actually performs a merge operation, which led to some extensive debug output because it basically printed the head() of the "right" dataframe. It would be helpful to be able to disable that behavior.

2021-03-24 14:47 UTC, koaning commented
I see the merit in this change but my first response is to consider referring to the parameter as `show_args` as opposed to `print_args`. @MBrouns just to check, got any comments on this?

2021-03-24 14:47 UTC, MBrouns commented
I see how that can be painful, and I think allowing users to select whether to print the args or not makes sense. I do have some comments which I'll put inline in the PR

2021-03-24 14:48 UTC, MBrouns commented
Oh right, `show_args` or `display_args` makes more sense than `print_args` as the latter implies that they're args that get passed to the `print` function

2021-03-24 14:50 UTC, MBrouns requested changes

2021-03-24 14:50 UTC, MBrouns commented on sklego/pandas_utils.py
> +            print_fn(f"[{func.__name__}()")
The formatting here is a bit off. 
```suggestion
            print_fn(f"[{func.__name__}]" + combined,)
```

2021-03-24 14:50 UTC, MBrouns commented on sklego/pandas_utils.py
>          func_args_str = "".join(
`inspect.signature` only needs to happen if we print the args, so it's probably better to move it into the `if` statement below

2021-03-24 14:54 UTC, daimonie commented
Hey guys, 

That was quick :) I made the suggested changes. I agree,   `display_args`  is the better name

2021-03-24 14:57 UTC, MBrouns commented
👍 

One (I think) last thing, could you add a test case to the `tests/pandas_utils.py`? There are already some examples on how you can test what output gets printed

2021-03-25 10:43 UTC, MBrouns commented on tests/test_pandas_utils/test_pandas_utils.py
> +    """Base test of log_step without any arguments to the logger"""
```suggestion
    """Test that we can disable printing function arguments in the log_step""
```

2021-03-25 10:46 UTC, MBrouns approved these changes

2021-03-25 10:54 UTC, MBrouns commented on tests/test_pandas_utils/test_pandas_utils.py
> +    """Test that we can disable printing function arguments in the log_step""
```suggestion
    """Test that we can disable printing function arguments in the log_step"""
```

2021-03-25 12:14 UTC, merged

2021-03-25 12:14 UTC, MBrouns commented
Thanks for the pr @daimonie!

2021-03-25 12:46 UTC, daimonie commented
Haha, thanks for the library @MBrouns  @koaning